//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Comments = new HashSet<Comment>();
            this.HireBookDetails = new HashSet<HireBookDetail>();
        }

        //Design pattern: Prototype
        public Book ShallowCopy()
        {
            return (Book)this.MemberwiseClone();
        }
        
    
        public int ID_Book { get; set; }
        public string Book_Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public double PriceImport { get; set; }
        public int PriceHire { get; set; }
        public System.DateTime DateImport { get; set; }
        public int Chapter { get; set; }
        public string Link { get; set; }
        public int ID_BookCategory { get; set; }
        public int Author_ID { get; set; }
        
    
        public virtual Author Author { get; set; }
        public virtual BookCategory BookCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HireBookDetail> HireBookDetails { get; set; }
    }
}
