//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense
    {
        public int ID_Expense { get; set; }
        public Nullable<System.DateTime> Date_Expense { get; set; }
        public Nullable<double> Price { get; set; }
        public string Describe_Expense { get; set; }
    }
}
